<a href="https://colab.research.google.com/github/telnarayanan/Pytorch-LearningProgress/blob/main/C0PytorchFundamentalsMrDBourke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'1.12.1+cu113'

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb


#Introduction to Tensors
 - Represent data in a numerical way
 - Image can be represented as a tensor with shape [3,224,224], meaning [color_channels, height, width]
 - In tensor speak, the tensor would have three dimensions. [color_channels, height, width]

#Scalar
 - Zero Dimension Tensor
 

In [ ]:
scalar = torch.tensor(5)
print(f"scalar {scalar}")
print(f"tensor dimension {scalar.ndim}")
print(f"Get python number within a tensor: Scalar Item {scalar.item()}")
print(f"Scalar shape: {scalar.shape}")

scalar 5
tensor dimension 0
Get python number within a tensor: Scalar Item 5
Scalar shape: torch.Size([])


#Vector
 - Vector is a single dimension tensor, but may contain numbers.
 - Eg, vector[3,2] would be [bedrooms, bathrooms] , or you could have [3,2,2] to describe [bedrooms, bathrooms, car_parks] in your house.
 
    

In [ ]:
vector = torch.tensor([3,2])
print(f"Vector: {vector}")
print(f"Vector Dimension: {vector.ndim}")
print(f"Vector Shape: {vector.shape}")

Vector: tensor([3, 2])
Vector Dimension: 1
Vector Shape: torch.Size([2])


# Matrix
 - Has two dimensions
 - As flexible as vectors, except that they've got extra dimension

In [ ]:
matrix = torch.tensor([[4,5],
                      [5,7]])
print(f"Matrix: {matrix}")
print(f"Matrix Dimension: {matrix.ndim}")
print(f"Matrix Shape: {matrix.shape}")

Matrix: tensor([[4, 5],
        [5, 7]])
Matrix Dimension: 2
Matrix Shape: torch.Size([2, 2])


The above matrix's size is 2x2, because Matrix is two elements deep and two elements wide.

# Tensor


In [ ]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[7,8,9]]])
print(f"TENSOR : {TENSOR}")
print(f"TENSOR Dimension: {TENSOR.ndim}")
print(f"TENSOR shape: {TENSOR.shape}")


TENSOR : tensor([[[1, 2, 3],
         [3, 6, 9],
         [7, 8, 9]]])
TENSOR Dimension: 3
TENSOR shape: torch.Size([1, 3, 3])


torch.size is [1,3,3], which means, that there's one dimension of 3 by 3.

# Random Tensors

- In Machine Learning models, it is rare to write out the tensors by hand. 
- We usually create a random tensor, and adjust these random tensors as it works through the data
- Here is the Tensor workflow
  - Start with Random Numbers
  - Look at data
  - Update Random numbers
  - Look at data
  - Update Random numbers, and so on

- torch.rand(), with size parameter

In [ ]:
random_tensor = torch.rand(size=(2,3,3))
print(f"Random Tensor: {random_tensor}")
print(f"Random Tensor datatype: {random_tensor.dtype}")
print(f"Random Tensor dimension: {random_tensor.ndim}")
print(f"Random Tensor shape: {random_tensor.shape}")

Random Tensor: tensor([[[0.2898, 0.3346, 0.6801],
         [0.5086, 0.2493, 0.1787],
         [0.0102, 0.6714, 0.5226]],

        [[0.7851, 0.0822, 0.1336],
         [0.8335, 0.9754, 0.8971],
         [0.8863, 0.3669, 0.5064]]])
Random Tensor datatype: torch.float32
Random Tensor dimension: 3
Random Tensor shape: torch.Size([2, 3, 3])


- Eg, random tensor of a common image shape of [3,224,224], [color_channels, height, width]

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))
print(f"Image tensor shape: {random_image_size_tensor.shape}")
print(f"Image tensor dimension: {random_image_size_tensor.ndim}")

Image tensor shape: torch.Size([3, 224, 224])
Image tensor dimension: 3


In [ ]:
print(f"Random image tensor printed: {random_image_size_tensor}" )

Random image tensor printed: tensor([[[7.1623e-02, 4.6310e-01, 6.5669e-01,  ..., 9.2430e-01,
          5.2114e-01, 8.6064e-01],
         [2.5475e-01, 1.2774e-01, 9.0934e-01,  ..., 9.8192e-01,
          2.5267e-01, 5.2331e-02],
         [9.1442e-01, 6.3809e-01, 7.9299e-01,  ..., 4.8927e-01,
          6.5216e-03, 1.7785e-01],
         ...,
         [2.4679e-01, 3.8188e-01, 1.3540e-02,  ..., 6.2077e-01,
          9.4418e-01, 6.1167e-01],
         [7.4730e-02, 2.3696e-01, 1.2463e-01,  ..., 1.8102e-01,
          3.9440e-01, 6.5327e-01],
         [4.9474e-01, 8.9180e-01, 6.4596e-01,  ..., 5.4779e-01,
          5.1792e-01, 6.1151e-01]],

        [[2.3179e-01, 7.1512e-02, 3.1849e-01,  ..., 5.5552e-02,
          7.8349e-01, 4.9540e-01],
         [5.6102e-01, 5.2438e-02, 9.9410e-01,  ..., 4.5864e-01,
          7.7197e-01, 8.1571e-01],
         [4.2984e-01, 1.7990e-01, 7.2067e-01,  ..., 2.1139e-01,
          6.3930e-01, 9.2122e-02],
         ...,
         [2.8593e-02, 7.5842e-01, 1.3184e-01,  ...

- Zeroes and Ones can be initialized as torch.zeros(size), and torch.ones(size)

# Tensor Operations
 - Addition
 - Subract
 - Elementwise Multiply
 - Divide
 - Matrix Multiply (MatMul)

# Matrix Multiplication
 - Most common Operations in ML and Dl algorithms
 - torch.matmul
 - Denoted by '@'
 - Two Rules
  - Inner Dimensions must match
  - Resulting Matrix has the shape of outer dimensions
   - Eg(2,3)@(3,2) -> (2,2) shape

In [ ]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
# Elementwise Multiply
print(f"Elementwise Multiplied -> Tensor * Tensor: {tensor*tensor}")

# Matmul
print(f"Matrix multiply -> Tensor @ Tensor {torch.matmul(tensor,tensor)}")

Elementwise Multiplied -> Tensor * Tensor: tensor([1, 4, 9])
Matrix multiply -> Tensor @ Tensor 14


In [ ]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 3.24 ms, sys: 43 µs, total: 3.28 ms
Wall time: 5.07 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 29 µs, sys: 6 µs, total: 35 µs
Wall time: 40.3 µs


tensor(14)

- Some common errors in DL would arise from multiplying two tensors of different dimensions. Here we can try transposing with tensor.transpose (.T) and then multiplying
- Torch.mm is the shortcut for torch.matmul
- Also referred as the dot product of two matrices

- Min, Max, Mean, Sum, Positional Min/Max
- Reshaping/Stacking/Squeezing/UnSqueezing
- Indexing (selecting data from tensors
- Torch.arange; Torch.reshape

# Reproducibility (take out the random from random)

- Neural Networks start with Random numbers to describe patterns in data, and try to improve those random numbers using Tensor operations.
 - Start with Random Numbers
 - Do Tensor Operations
 - Try to make it better

In [ ]:
import torch

# create two random tensors

tensorA = torch.rand(4,5)
tensorB = torch.rand(4,5)

print(f"Tensor A:\n {tensorA}")
print(f"Tensor B:\n {tensorB}")

print(f"Is Tensor A equal to Tensor B")
tensorA == tensorB

Tensor A:
 tensor([[0.4713, 0.2941, 0.3344, 0.0192, 0.6322],
        [0.0837, 0.2601, 0.6869, 0.4588, 0.5161],
        [0.2435, 0.7023, 0.3166, 0.9334, 0.7604],
        [0.0105, 0.0828, 0.4139, 0.0679, 0.9657]])
Tensor B:
 tensor([[0.8381, 0.5905, 0.4286, 0.9408, 0.3942],
        [0.5066, 0.1602, 0.2566, 0.6934, 0.2470],
        [0.7346, 0.0765, 0.1799, 0.9898, 0.6808],
        [0.3044, 0.9839, 0.4747, 0.1323, 0.6796]])
Is Tensor A equal to Tensor B


tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.random.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
!nvidia-smi

Sun Aug 21 11:05:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])