<a href="https://colab.research.google.com/github/telnarayanan/Pytorch-LearningProgress/blob/main/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
data = [
    [1,2],
    [3,4]
]
x_data = torch.tensor(data)

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"x_data :{x_data}\n")
print(f"x_ones : Ones Tensor shaped like x_data: {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

x_data :tensor([[1, 2],
        [3, 4]])

x_ones : Ones Tensor shaped like x_data: tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.2573, 0.1363],
        [0.2015, 0.2479]]) 



In [ ]:
shape=(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: {rand_tensor}\n")
print(f"ones_tensor: {ones_tensor}\n")
print(f"Zeros_tensor: {zeros_tensor}\n")

Random tensor: tensor([[3.4475e-01, 3.5969e-01, 8.5996e-01],
        [3.4601e-01, 5.3086e-01, 4.3964e-04]])

ones_tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros_tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [ ]:
#Attributes

x_tensor=torch.rand(5,6)

print(f"Shape of Tensor: {x_tensor.shape}")
print(f"Datatype of Tensor: {x_tensor.dtype}")
print(f"Device in which the tensor is stored on: {x_tensor.device}")

Shape of Tensor: torch.Size([5, 6])
Datatype of Tensor: torch.float32
Device in which the tensor is stored on: cpu


In [ ]:
#Operations on a Tensor
#Over 100 operations possible on a Tensor

if torch.cuda.is_available():
  x_tensor = x_tensor.to("cuda")

print(f"Device in which Tensor is stored on: {x_tensor.device}")

Device in which Tensor is stored on: cuda:0


In [ ]:
x_tensor=torch.ones(3,4)

print(f"First Row: {x_tensor[0]}")
print(f"First Column: {x_tensor[:,0]}")
print(f"Last column: {x_tensor[:,-1]}")
x_tensor[:,1] = 0

print(x_tensor)

First Row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#Joining Tensors
#torch.cat to join tensors, concatenate a sequence of tensors along given dimension.

t1 = torch.cat([x_tensor,x_tensor,x_tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
# MatMul

y1 = x_tensor@x_tensor.T
y2 = x_tensor.matmul(x_tensor.T)
y3 = torch.rand_like(y1)  
torch.matmul(x_tensor, x_tensor.T, out=y3)




tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [ ]:
# Element wise multiplication

z1 = x_tensor*x_tensor
z2 = x_tensor.mul(x_tensor)
z3 = torch.rand_like(x_tensor)
torch.mul(x_tensor, x_tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
# Single-element tensor
agg = x_tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

9.0 <class 'float'>


In [25]:
#inplace operations (with prior_)

print(f"{x_tensor}\n")
x_tensor.add_(10)
print(x_tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [31]:
#numpy and tensors have the same  memory locations, and are bridged.
#modifying the numpy, will also modify tensor value, and vice versa

#declare a new numpy array

data = [
    [4,5],
    [6,7],
    [8,9]
]
x_numpy = np.array(data)

#copy the numpy array to the tensor

x_newtensor = torch.from_numpy(x_numpy)

#print them both 

print(f"Numpy value: \n{x_numpy}\n")
print(f"Tensor value:\n{x_newtensor}\n")

#modify the tensor array, and print it

x_newtensor.add_(1)
print(f"New Tensor, with 1 added inplace: \n {x_newtensor} \n")

#check if numpy has changed
print(f"Checking Numpy: \n{x_numpy}\n")

Numpy value: 
[[4 5]
 [6 7]
 [8 9]]

Tensor value:
tensor([[4, 5],
        [6, 7],
        [8, 9]])

New Tensor, with 1 added inplace: 
 tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]]) 

Checking Numpy: 
[[ 5  6]
 [ 7  8]
 [ 9 10]]

